### PR TITLE
Upgrade jaxrsAnalyzer version to 0.12

### PR DESCRIPTION
**Pull request by verkhoro**
- increment minor version because extra options make it incompatible with 0.9 and below
- didn't figure out how to make all new options configurable (and optional in case of the -cp and -sp). May look into this later if it's necessary

### CODE REVIEW

**Comment by SerialVelocity** [comment]
@eshepelyuk Can this be merged?

@verkhoro Maybe worth updating to 0.14?

**Comment by verkhoro** [comment]
@SerialVelocity my project ended up rejecting the feature based

**Comment by verkhoro** [comment]
@SerialVelocity my project isn't using jaxrs-analyzer or this plugin, so I don't have a need to maintain compatibility with the latest versions

**Comment by eshepelyuk** [comment]
Published `v0.2.0`, jaxrsAnalyzer updated to 0.14

**Pull request merged**
